@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo5LCJleHAiOjE2MzU5NDg5NzJ9.og_5SV1lwJh6EMhwo12dui0-LDYYvrZ2vqwgPItKE0g

### Users Index
GET http://localhost:3000/users

### Users Create
POST http://localhost:3000/users.json
Content-Type: application/json
  
  {
    "first_name": "testuser1",
    "last_name": "testuser1",
    "email": "testuser3@test.com",
    "password": "password",
    "password_confirmation": "password",
    "job": "test job",
    "location": "test location",
    "bio": "test bio"
  }


### User Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

  {
    "email": "testuser3@test.com",
    "password": "password"
  }

### Rater Sessions create (login)
POST http://localhost:3000/rater_sessions
Content-Type: application/json

{ 
  "email": "rater1@test.com",
  "password": "password"
}

### Photos Index
GET http://localhost:3000/photos
Authorization: Bearer {{jwt}}
Content-Type: application/json

### Photos create
POST http://localhost:3000/photos
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "img_url": "https://cdn2.vectorstock.com/i/1000x1000/92/26/user-silhouette-with-question-mark-icon-vector-8989226.jpg"
}


### Photos update
PATCH http://localhost:3000/photos/17.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "img_url": "https://cdn2.iconfinder.com/data/icons/flat-style-svg-icons-part-1/512/check_user_man-512.png"
}

### Photos Destroy
DELETE http://localhost:3000/photos/17
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Ratings Create
POST http://localhost:3000/ratings
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "description": "This photo is too blury",
  "score_for_photo": 50,
  "rater_feed_back": 1
}


### Raters Create

POST http://localhost:3000/raters.json
Content-Type: application/json
  
  {
    "first_name": "testuser1",
    "last_name": "testuser1",
    "email": "testuser3@test.com",
    "password": "password",
    "password_confirmation": "password"
  }
